artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/016c6327a6d54c3bbd83660d9c4eef7f/artifacts
end_time: 1746522742395
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 016c6327a6d54c3bbd83660d9c4eef7f
run_name: Default
run_uuid: 016c6327a6d54c3bbd83660d9c4eef7f
source_name: ''
source_type: 4
source_version: ''
start_time: 1746522742358
status: 4
tags: []
user_id: mle-user
