artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/mlflow_experiments_store/0/3b88b2b13c634b49b56bd70a9749d753/artifacts
end_time: 1746522679314
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3b88b2b13c634b49b56bd70a9749d753
run_name: Default
run_uuid: 3b88b2b13c634b49b56bd70a9749d753
source_name: ''
source_type: 4
source_version: ''
start_time: 1746522679238
status: 3
tags: []
user_id: mle-user
