artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f8c201c95a47444e85b0df388b7df44c/artifacts
end_time: 1746522799888
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f8c201c95a47444e85b0df388b7df44c
run_name: Default
run_uuid: f8c201c95a47444e85b0df388b7df44c
source_name: ''
source_type: 4
source_version: ''
start_time: 1746522799868
status: 3
tags: []
user_id: mle-user
