artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/4bdf2cf6475547db89d38605b67c0992/artifacts
end_time: 1746523105843
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4bdf2cf6475547db89d38605b67c0992
run_name: Default
run_uuid: 4bdf2cf6475547db89d38605b67c0992
source_name: ''
source_type: 4
source_version: ''
start_time: 1746523105781
status: 3
tags: []
user_id: mle-user
