artifact_location: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/493993512728296317
creation_time: 1746527983590
experiment_id: '493993512728296317'
last_update_time: 1746527983590
lifecycle_stage: active
name: test_connection_experiment_Pyankov_do
