artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/6398fa427a27416e9e9d325d43fe3b44/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6398fa427a27416e9e9d325d43fe3b44
run_name: rare-loon-609
run_uuid: 6398fa427a27416e9e9d325d43fe3b44
source_name: ''
source_type: 4
source_version: ''
start_time: 1746528093521
status: 1
tags: []
user_id: mle-user
